FROM golang:1.16 as builder

RUN apt-get update && apt-get install -y upx

ADD . ${GOPATH}/src/github.com/cbrand/mdnsforwarder

WORKDIR ${GOPATH}/src/github.com/cbrand/mdnsforwarder

RUN go build -trimpath -ldflags="-s -w" -o /opt/mdnsforwarder cli/mdnsforwarder.go

RUN upx -9 /opt/mdnsforwarder

FROM alpine:3.13

RUN apk add --no-cache libc6-compat

COPY --from=builder /opt/mdnsforwarder /opt/mdnsforwarder

CMD [ "/opt/mdnsforwarder" ]
